AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MainbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bot-main/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        BotMain:
          Type: Api
          Properties:
            Path: /bot-main
            Method: post
      Environment:
        Variables:
          BOT_TOKEN: '{{resolve:ssm:IlovethisgameBotToken:2}}'
          AIRTABLE_TOKEN: '{{resolve:ssm:IlovethisgameAirtableToken:1}}'
          AIRTABLE_BASE: '{{resolve:ssm:IlovethisgameAirtableBase:1}}'
          LIVESCORE_KEY: '{{resolve:ssm:IlovethisgameLivescoreKey:1}}'
          LIVESCORE_SECRET: '{{resolve:ssm:IlovethisgameLivescoreSecret:1}}'

  # ProcessDynamoDBStream:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: handler
  #     Runtime: runtime
  #     Policies: AWSLambdaDynamoDBExecutionRole
  #     Events:
  #       Stream:
  #         Type: DynamoDB
  #         Properties:
  #           Stream: !GetAtt DynamoDBTable.StreamArn
  #           BatchSize: 100
  #           StartingPosition: TRIM_HORIZON

  # DynamoDBTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     AttributeDefinitions:
  #       - AttributeName: userid
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: userid
  #         KeyType: HASH
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 5
  #       WriteCapacityUnits: 5
  #     StreamSpecification:
  #       StreamViewType: NEW_AND_OLD_IMAGES


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MainbotApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bot-main/"
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
